name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --manifest-path /home/runner/work/MP3-Metadata-Extractor/MP3-Metadata-Extractor/mp3_metadata_extractor/Cargo.toml --verbose
    - name: Run 
      run: cargo run --manifest-path /home/runner/work/MP3-Metadata-Extractor/MP3-Metadata-Extractor/mp3_metadata_extractor/Cargo.toml --verbose
